# Generated by Django 4.2.4 on 2023-10-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contra',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
    ]
