# Generated by Django 4.2.4 on 2023-10-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0002_remove_usuario_contra_remove_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(default='L', max_length=1),
        ),
    ]
