# Generated by Django 4.2.4 on 2023-10-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0003_usuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='num_cuenta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
