# Generated by Django 4.2.4 on 2023-11-14 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0004_remove_usuario_num_cuenta_usuario_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='fecha',
            new_name='fecha_final',
        ),
        migrations.AddField(
            model_name='eventos',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
