# Generated by Django 4.2.4 on 2023-11-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0005_rename_fecha_eventos_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_evento'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_publicacion'),
        ),
    ]
