# Generated by Django 4.2.4 on 2023-11-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0006_alter_eventos_imagen_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='imagen',
        ),
    ]
